# Generated by Django 5.2.6 on 2025-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(default='settings.MEDIA_ROOT/default_event.jpg', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='foods',
            field=models.ManyToManyField(related_name='events', to='event.fooditem'),
        ),
    ]
