# Generated by Django 5.2.6 on 2025-09-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_transaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(default='Wallet', max_length=20),
        ),
    ]
