# Generated by Django 5.2.6 on 2025-09-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_delete_wallettransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
