# Generated by Django 5.2.6 on 2025-09-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_delete_transaction'),
        ('user', '0003_wallettransaction_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
    ]
